### ISSUE TITLE
Space Exploration and Alien Biomes support 

### ISSUE THREAD

**Issue by TehFreek** [TheStrath/DeleteEmptyChunks#2]
I was going to do this as a PR but `control.lua` seems to have a mix of line endings so here's a patch instead.

[dec-seab.patch.gz](https://github.com/TheStrath/DeleteEmptyChunks/files/3437565/dec-seab.patch.gz)

**Comment by Delta-VII** [comment]
Dumb question, how do you apply the patch?

**Comment by TehFreek** [comment]
In the repo root:

    zcat path/to/dec-seab.patch.gz | git apply --whitespace=fix

**Comment by TheStrath** [comment]
Support for Alien Biome and Space Exploration added in version 0.3.8
